### ISSUE TITLE
Crash when choose file inside archive file (zip, etc)

### ISSUE THREAD

**Issue by corvinav** [coomar2841/android-multipicker-library#113]
Hi. I have crash when I choose file inside archive file (zip, etc)
Actually I don't need enter inside archive and I just want to get archive but it enters inside archive after click on archive file.
Log:
`E/AndroidRuntime: FATAL EXCEPTION: Thread-11
                                                               Process: com.test, PID: 26884
                                                               java.lang.NumberFormatException: For input string: "4986:base.sqlite3"
                                                                   at java.lang.Long.parseLong(Long.java:443)
                                                                   at java.lang.Long.valueOf(Long.java:542)
                                                                   at com.kbeanie.multipicker.core.threads.FileProcessorThread.getPathAndMimeType(FileProcessorThread.java:367)
                                                                   at com.kbeanie.multipicker.core.threads.FileProcessorThread.getAbsolutePathIfAvailable(FileProcessorThread.java:343)
                                                                   at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:169)
                                                                   at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
                                                                   at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)`

Crash it isn't very good, but are there any way to avoid opening archive files and just pick it.

PS. Thank you for a good library.

**Comment by coomar2841** [comment]
What file picker you are using? Can you send me a screenshot where the zip archive is displayed?

**Comment by corvinav** [comment]
I did some investigations(emulator) and noticed that it depend from android version(maybe), because at some versions file picker select archive file and all was ok,  but at some versions file picker goes inside archive and I can select file inside archive and have a crash.
I'll provide some addishional information later.
But at this moment I noticed if you choice file inside archive android file picker lib return URI ending with "id_arch:file_name" and you don't process this case.
