### ISSUE TITLE
Illegal Argument Exception while taking a picture from camera

### ISSUE THREAD

**Issue by FarhanAhmad** [coomar2841/android-multipicker-library#132]
Hi,
I am getting following crash on my device. Details are as follows:

Device: Huawei P10 Plus.
OS: Android 7.0
Crash: 
E/UncaughtException: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.app/files/pictures/10ac2954-6495-4555-ad58-a4e275c54ed3.jpeg
                                                                              at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:719)
                                                                              at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:404)
                                                                              at com.kbeanie.multipicker.core.ImagePickerImpl.takePictureWithCamera(ImagePickerImpl.java:145)
                                                                              at com.kbeanie.multipicker.core.ImagePickerImpl.pick(ImagePickerImpl.java:121)
                                                                              at com.kbeanie.multipicker.api.CameraImagePicker.pickImage(CameraImagePicker.java:81)
                                                                              at com.app.AppActivity.pickImage(AppActivity.java:1625)
                                                                              at com.app.AppActivity.onBottomSheetAction(AppActivity.java:1614)
                                                                              at com.app.AppFragments.AppBottomSheet.onClick(AppBottomSheet.java:58)
                                                                              at android.view.View.performClick(View.java:5647)
                                                                              at android.view.View$PerformClick.run(View.java:22479)
                                                                              at android.os.Handler.handleCallback(Handler.java:761)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by FarhanAhmad** [comment]
provider needs to be fixed as i was already using a provider.
