### ISSUE TITLE
Crash in Samsung SM-G530H model Capture Image

### ISSUE THREAD

**Issue by dhavalappspool** [coomar2841/android-multipicker-library#142]
When Camera open and capture the image then click ok to crash the app

06-28 13:07:24.527 3795-3795/? W/System.err: java.io.FileNotFoundException: /efs/carrier/HiddenMenu: open failed: ENOENT (No such file or directory)
06-28 13:07:24.537 3795-3795/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
06-28 13:07:24.537 3795-3795/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
06-28 13:07:24.537 3795-3795/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:103)
06-28 13:07:24.537 3795-3795/? W/System.err:     at java.io.FileReader.<init>(FileReader.java:66)
06-28 13:07:24.537 3795-3795/? W/System.err:     at com.sec.android.app.parser.KeystringCommon.checkHiddnemenu(KeystringCommon.java:378)
06-28 13:07:24.537 3795-3795/? W/System.err:     at com.sec.android.app.parser.KeystringCommon.updateHiddnemenu(KeystringCommon.java:399)
06-28 13:07:24.537 3795-3795/? W/System.err:     at com.sec.android.app.parser.KeystringCommon.<init>(KeystringCommon.java:107)
06-28 13:07:24.537 3795-3795/? W/System.err:     at com.sec.android.app.parser.ParseService.onCreate(ParseService.java:121)
06-28 13:07:24.537 3795-3795/? W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3112)
06-28 13:07:24.537 3795-3795/? W/System.err:     at android.app.ActivityThread.access$1900(ActivityThread.java:168)
06-28 13:07:24.537 3795-3795/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
06-28 13:07:24.537 3795-3795/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-28 13:07:24.537 3795-3795/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
06-28 13:07:24.537 3795-3795/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5753)
06-28 13:07:24.537 3795-3795/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-28 13:07:24.537 3795-3795/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-28 13:07:24.537 3795-3795/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
06-28 13:07:24.537 3795-3795/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
06-28 13:07:24.537 3795-3795/? W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-28 13:07:24.537 3795-3795/? W/System.err:     at libcore.io.Posix.open(Native Method)
06-28 13:07:24.537 3795-3795/? W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-28 13:07:24.537 3795-3795/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
06-28 13:07:24.537 3795-3795/? W/System.err:     ... 17 more
06-28 13:07:24.537 1156-1156/? W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
06-28 13:07:24.557 992-1022/? W/ActivityManager: mDVFSHelper.release()
06-28 13:07:24.557 3534-3582/? E/OpenGLRenderer: SFEffectCache:clear(), mSize = 0
06-28 13:07:24.567 3795-3795/? W/System.err: java.io.FileNotFoundException: /efs/carrier/HiddenMenu: open failed: ENOENT (No such file or directory)
06-28 13:07:24.567 3795-3795/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
06-28 13:07:24.567 3795-3795/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
06-28 13:07:24.567 3795-3795/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:103)
06-28 13:07:24.567 3795-3795/? W/System.err:     at java.io.FileReader.<init>(FileReader.java:66)
06-28 13:07:24.567 3795-3795/? W/System.err:     at com.sec.android.app.parser.KeystringCommon.checkHiddnemenu(KeystringCommon.java:378)
06-28 13:07:24.567 3795-3795/? W/System.err:     at com.sec.android.app.parser.KeystringCommon.updateHiddnemenu(KeystringCommon.java:399)
06-28 13:07:24.567 3795-3795/? W/System.err:     at com.sec.android.app.parser.ParseService.initialize(ParseService.java:184)
06-28 13:07:24.567 3795-3795/? W/System.err:     at com.sec.android.app.parser.ParseService.onCreate(ParseService.java:127)
06-28 13:07:24.567 3795-3795/? W/System.err:     at android.app.ActivityThread.handleCreateService(ActivityThread.java:3112)
06-28 13:07:24.567 3795-3795/? W/System.err:     at android.app.ActivityThread.access$1900(ActivityThread.java:168)
06-28 13:07:24.567 3795-3795/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1476)
06-28 13:07:24.567 3795-3795/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-28 13:07:24.567 3795-3795/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
06-28 13:07:24.567 3795-3795/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5753)
06-28 13:07:24.567 3795-3795/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-28 13:07:24.567 3795-3795/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-28 13:07:24.567 3795-3795/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
06-28 13:07:24.567 3795-3795/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
06-28 13:07:24.567 3795-3795/? W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-28 13:07:24.567 3795-3795/? W/System.err:     at libcore.io.Posix.open(Native Method)
06-28 13:07:24.567 3795-3795/? W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-28 13:07:24.567 3795-3795/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
06-28 13:07:24.567 3795-3795/? W/System.err:     ... 17 more
06-28 13:07:24.587 3795-3795/? W/System.err: java.io.FileNotFoundException: /efs/carrier/HiddenMenu: open failed: ENOENT (No such file or directory)
06-28 13:07:24.587 3795-3795/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:456)
06-28 13:07:24.587 3795-3795/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
06-28 13:07:24.587 3795-3795/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:103)
06-28 13:07:24.587 3795-3795/? W/System.err:     at java.io.FileReader.<init>(FileReader.java:66)
06-28 13:07:24.587 3795-3795/? W/System.err:     at com.sec.android.app.parser.KeystringCommon.checkHiddnemenu(KeystringCommon.java:378)
06-28 13:07:24.587 3795-3795/? W/System.err:     at com.sec.android.app.parser.KeystringCommon.updateHiddnemenu(KeystringCommon.java:399)
06-28 13:07:24.587 3795-3795/? W/System.err:     at com.sec.android.app.parser.ParseService.initialize(ParseService.java:184)
06-28 13:07:24.587 3795-3795/? W/System.err:     at com.sec.android.app.parser.ParseService.onStartCommand(ParseService.java:169)
06-28 13:07:24.587 3795-3795/? W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3266)
06-28 13:07:24.587 3795-3795/? W/System.err:     at android.app.ActivityThread.access$2200(ActivityThread.java:168)
06-28 13:07:24.587 3795-3795/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1491)
06-28 13:07:24.587 3795-3795/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-28 13:07:24.587 3795-3795/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
06-28 13:07:24.587 3795-3795/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5753)
06-28 13:07:24.587 3795-3795/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-28 13:07:24.587 3795-3795/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
06-28 13:07:24.587 3795-3795/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
06-28 13:07:24.587 3795-3795/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
06-28 13:07:24.587 3795-3795/? W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
06-28 13:07:24.587 3795-3795/? W/System.err:     at libcore.io.Posix.open(Native Method)
06-28 13:07:24.587 3795-3795/? W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
06-28 13:07:24.587 3795-3795/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:442)
06-28 13:07:24.587 3795-3795/? W/System.err:     ... 17 more

**Comment by coomar2841** [comment]
Looks like a permissions issue. Can you check if the same image works for the sample app?

https://play.google.com/store/apps/details?id=com.kbeanie.multipicker.sample&hl=en_AU

**Comment by dhavalappspool** [comment]
same issues in sample app
