### ISSUE TITLE
Getting IllegalArgumentException 

### ISSUE THREAD

**Issue by vishrut2207** [coomar2841/android-multipicker-library#158]
Fatal Exception: java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/2483
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
       at android.content.ContentResolver.query(ContentResolver.java:760)
       at android.content.ContentResolver.query(ContentResolver.java:710)
       at android.content.ContentResolver.query(ContentResolver.java:668)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.getDataAndMimeType(FileProcessorThread.java:445)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.getPathAndMimeType(FileProcessorThread.java:50039)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:2190)
       at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:42)

**Comment by DummyCo** [comment]
Same here:
```
    java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/8408
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:802)
        at android.content.ContentResolver.query(ContentResolver.java:752)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getDataAndMimeType(FileProcessorThread.java:419)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getPathAndMimeType(FileProcessorThread.java:370)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getAbsolutePathIfAvailable(FileProcessorThread.java:344)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:170)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)
```
Looks like related to downloads file picking,
Pixel XL, Android 9
@coomar2841, address this please.

**Comment by ericksli** [comment]
I got the same issue as well

I am using emulator (Android 9)

```
2018-11-15 11:03:13.378 8072-8384/com.example.foo E/AndroidRuntime: FATAL EXCEPTION: Thread-17
    Process: com.example.foo, PID: 8072
    java.lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/18
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:418)
        at android.content.ContentResolver.query(ContentResolver.java:802)
        at android.content.ContentResolver.query(ContentResolver.java:752)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getDataAndMimeType(FileProcessorThread.java:419)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getPathAndMimeType(FileProcessorThread.java:370)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getAbsolutePathIfAvailable(FileProcessorThread.java:344)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:170)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)
        at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:42)
```

**Comment by vijay3** [comment]
The issue is fixed on 14 November, 2018. (Version 1.6)
Commit ID: 72fea9c13e36eb7a69f34b52d9a37e8266ba1a1c

But folks are unable to add 1.6 version as gradle is unable to resolve it.
The issue is already reported. Hope it gets resolved soon.

**Comment by coomar2841** [comment]
Can you check with 1.6?

**Comment by vishrut2207** [comment]
After update App is not crashing but I am not able to pick that image. it is throwing PickerException.

**Comment by coomar2841** [comment]
Can you please post the logs

**Comment by vishrut2207** [comment]
@coomar2841 I have updated below code and its work perfectly in **Android 8.1.0, 7.1.1, 6.0** 

```
if (isDownloadsDocument(uri)) {
                final String id = DocumentsContract.getDocumentId(uri);
                if (id.startsWith("raw:")) {
                    String[] data = new String[2];
                    data[0] = id.replaceFirst("raw:", "");
                    data[1] = null;
                    return data;
                }
                Uri contentUri = uri;

                String[] contentUriPrefixesToTry = new String[]{
                        "content://downloads/public_downloads",
                        "content://downloads/my_downloads"
                };

                if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {

                    for (String contentUriPrefix : contentUriPrefixesToTry) {
                        contentUri = ContentUris.withAppendedId(Uri.parse(contentUriPrefix), Long.valueOf(id));
                        try {
                            String[] data = getDataAndMimeType(contentUri, null, null, file.getType());
                            if (data != null) {
                                return data;
                            }
                        } catch (Exception ignored) {
                        }
                    }

                } else {
                    return getDataAndMimeType(contentUri, null, null, file.getType());
                }
            }
```

**Comment by anggit97** [comment]
> @coomar2841 I have updated below code and its work perfectly in **Android 8.1.0, 7.1.1, 6.0**
> 
> ```
> if (isDownloadsDocument(uri)) {
>                 final String id = DocumentsContract.getDocumentId(uri);
>                 if (id.startsWith("raw:")) {
>                     String[] data = new String[2];
>                     data[0] = id.replaceFirst("raw:", "");
>                     data[1] = null;
>                     return data;
>                 }
>                 Uri contentUri = uri;
> 
>                 String[] contentUriPrefixesToTry = new String[]{
>                         "content://downloads/public_downloads",
>                         "content://downloads/my_downloads"
>                 };
> 
>                 if (Build.VERSION.SDK_INT < Build.VERSION_CODES.N) {
> 
>                     for (String contentUriPrefix : contentUriPrefixesToTry) {
>                         contentUri = ContentUris.withAppendedId(Uri.parse(contentUriPrefix), Long.valueOf(id));
>                         try {
>                             String[] data = getDataAndMimeType(contentUri, null, null, file.getType());
>                             if (data != null) {
>                                 return data;
>                             }
>                         } catch (Exception ignored) {
>                         }
>                     }
> 
>                 } else {
>                     return getDataAndMimeType(contentUri, null, null, file.getType());
>                 }
>             }
> ```

what is getDataAndMimeType function?
