### ISSUE TITLE
Fatal Exception: android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by vishrut2207** [coomar2841/android-multipicker-library#161]
issue is not getting every time but some time suddenly crash.

Android Version : **4.4.2, 4.4.3 , 5.0, 5.0.2, 5.1, 5.1.1, 7.0, 7.1.1, 7.1.2, 8.0.0, 8.1.0**
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:content://com.app.imagepicker.multipicker.fileprovider/photos/359ccd83-62fe-4ac2-a47f-d9c039325531.jpeg} (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2031)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1686)
       at android.app.Activity.startActivityForResult(Activity.java:4506)
       at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
       at android.app.Activity.startActivityForResult(Activity.java:4464)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
       at com.kbeanie.multipicker.core.PickerManager.pickInternal(PickerManager.java:172)
       at com.kbeanie.multipicker.core.ImagePickerImpl.takePictureWithCamera(ImagePickerImpl.java:1171)
       at com.kbeanie.multipicker.api.CameraImagePicker.pickImage(CameraImagePicker.java:81)
       at com.ui.fragment.new_version.NEWEditorFragment.cameraImg(NEWEditorFragment.java:50528)
       at com.ui.fragment.new_version.NEWEditorFragment$30.onDialogClick$9742912(NEWEditorFragment.java:3320)
       at com.ui.dialog.BaseDialogFragment.createDialog(BaseDialogFragment.java:87)
       at com.ui.dialog.OptionListDialog.onClick(OptionListDialog.java:75)
       at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1142)
       at android.widget.AdapterView.performItemClick(AdapterView.java:318)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1158)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3153)
       at android.widget.AbsListView.onTouchUp(AbsListView.java:4080)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3839)
       at android.view.View.dispatchTouchEvent(View.java:11779)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2965)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2643)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2971)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2971)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2971)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2971)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2971)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2657)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:477)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
       at android.app.Dialog.dispatchTouchEvent(Dialog.java:815)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:439)
       at android.view.View.dispatchPointerEvent(View.java:12018)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4829)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4643)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4181)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4234)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4200)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4327)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4208)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4384)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4181)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4234)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4200)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4208)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4181)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6744)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6683)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6644)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6847)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:193)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6626)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Comment by FAndSec** [comment]
Based on the stack trace, adding the below statement above PickerManager.java:172 may fix the crash:
if(null!=intent.resolveActivity(activity.getPackageManager()))

**Comment by coomar2841** [comment]
Do you know on what devices this issue occurs?

**Comment by deepbhavsar** [comment]
I am facing issue into the below device @coomar2841 

**Device**
Brand: TrendMicro
Model: GI-I9500_TMMARS
Orientation: Portrait
RAM free: 20.64 GB
Disk free: 40.09 GB
**Operating System**
Version: 5.1
Orientation: Portrait
Rooted: Yes
