### ISSUE TITLE
IllegalArgumentException when selecting a file from the Downloads folder on Android 7

### ISSUE THREAD

**Issue by elephant-cf** [coomar2841/android-multipicker-library#166]
Android 7.

see a similar problem description and solution here
https://stackoverflow.com/questions/52750508/accessing-public-download-files-onactivityresult-android-28-samsung-galaxy-s9

lang.IllegalArgumentException: Unknown URI: content://downloads/public_downloads/353
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at android.content.ContentResolver.query(ContentResolver.java:532)
        at android.content.ContentResolver.query(ContentResolver.java:473)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getDataAndMimeType(FileProcessorThread.java:419)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getPathAndMimeType(FileProcessorThread.java:370)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.getAbso lutePathIfAvailable(FileProcessorThread.java:344)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:170)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
        at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)

**Comment by elephant-cf** [comment]
Мodifed working version

[FileProcessorThread.txt](https://github.com/coomar2841/android-multipicker-library/files/3058285/FileProcessorThread.txt)

**Comment by kansalmohit19** [comment]
Hi,

I am facing the same issue in Android 8. Please help!
