### ISSUE TITLE
Nexus 5 (Android 6.0.1) Video Recording -> postProcessVideo: Error generating metadata

### ISSUE THREAD

**Issue by NoelChew** [coomar2841/android-multipicker-library#17]
I got the errors below when I am trying to record video for Nexus 5 with Android 6.0.1. I have tested with the following camera apps:
Camera - Version 3.2.042 (2770680-30)
CameraMX - Version 3.5.003
```
04-29 12:02:34.258 5233-5233/com.kbeanie.multipicker.sample D/VideoPickerImpl: Temp Path for Camera capture: /storage/emulated/0/And Multipicker Demo/And Multipicker Demo Movies/f1a3c14b-a0e0-4f2c-887e-fb7cc0edcccb.mp4
04-29 12:02:34.527 5233-5233/com.kbeanie.multipicker.sample I/Ads: Scheduling ad refresh 60000 milliseconds from now.
04-29 12:02:34.532 5233-5233/com.kbeanie.multipicker.sample I/Ads: Ad finished loading.
04-29 12:02:42.531 5233-5233/com.kbeanie.multipicker.sample D/VideoPickerImpl: handleCameraData: /storage/emulated/0/And Multipicker Demo/And Multipicker Demo Movies/f1a3c14b-a0e0-4f2c-887e-fb7cc0edcccb.mp4
04-29 12:02:42.558 5233-6522/com.kbeanie.multipicker.sample D/FileProcessorThread: processFile: Before: Type: video, QueryUri: file:///storage/emulated/0/And%20Multipicker%20Demo/And%20Multipicker%20Demo%20Movies/f1a3c14b-a0e0-4f2c-887e-fb7cc0edcccb.mp4, Original Path: null, MimeType: null, Size: 0 B
04-29 12:02:42.561 5233-6522/com.kbeanie.multipicker.sample D/FileProcessorThread: processFile: Final Path: Type: video, QueryUri: file:///storage/emulated/0/And%20Multipicker%20Demo/And%20Multipicker%20Demo%20Movies/f1a3c14b-a0e0-4f2c-887e-fb7cc0edcccb.mp4, Original Path: /storage/emulated/0/And Multipicker Demo/And Multipicker Demo Movies/f1a3c14b-a0e0-4f2c-887e-fb7cc0edcccb.mp4, MimeType: video/mp4, Size: 0 B
04-29 12:02:42.563 5233-6522/com.kbeanie.multipicker.sample D/VideoProcessorThread: postProcessVideo: Error generating metadata
04-29 12:02:42.563 5233-6522/com.kbeanie.multipicker.sample W/System.err: java.lang.IllegalArgumentException
04-29 12:02:42.565 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:73)
04-29 12:02:42.565 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at com.kbeanie.multipicker.core.threads.VideoProcessorThread.postProcessVideo(VideoProcessorThread.java:66)
04-29 12:02:42.565 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at com.kbeanie.multipicker.core.threads.VideoProcessorThread.postProcessVideos(VideoProcessorThread.java:53)
04-29 12:02:42.565 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at com.kbeanie.multipicker.core.threads.VideoProcessorThread.run(VideoProcessorThread.java:45)
04-29 12:02:42.577 5233-6522/com.kbeanie.multipicker.sample W/System.err: com.kbeanie.multipicker.api.exceptions.PickerException: Error while generating thumbnail: 1 null
04-29 12:02:42.577 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.downScaleAndSaveImage(FileProcessorThread.java:729)
04-29 12:02:42.577 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at com.kbeanie.multipicker.core.threads.VideoProcessorThread.postProcessVideo(VideoProcessorThread.java:106)
04-29 12:02:42.577 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at com.kbeanie.multipicker.core.threads.VideoProcessorThread.postProcessVideos(VideoProcessorThread.java:53)
04-29 12:02:42.577 5233-6522/com.kbeanie.multipicker.sample W/System.err:     at com.kbeanie.multipicker.core.threads.VideoProcessorThread.run(VideoProcessorThread.java:45)
04-29 12:02:42.618 5233-5233/com.kbeanie.multipicker.sample D/MediaResultsAdapter: getView: 1
04-29 12:02:42.661 5233-5233/com.kbeanie.multipicker.sample D/MediaResultsAdapter: getView: 1
04-29 12:02:50.313 5233-5241/com.kbeanie.multipicker.sample E/System: Uncaught exception thrown by finalizer
04-29 12:02:50.313 5233-5241/com.kbeanie.multipicker.sample E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'void dalvik.system.CloseGuard.close()' on a null object reference
                                                                          at java.io.FileInputStream.close(FileInputStream.java:113)
                                                                          at java.io.FileInputStream.finalize(FileInputStream.java:140)
                                                                          at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                                                          at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                                                          at java.lang.Thread.run(Thread.java:818)
```

**Comment by coomar2841** [comment]
Which version of library are you using?

**Comment by NoelChew** [comment]
0.99

**Comment by coomar2841** [comment]
Fixed. Can you please check and verify with version `1.0.10`?

**Comment by NoelChew** [comment]
Confirmed fixed. Thanks!
