### ISSUE TITLE
Upgrade to 1.6.1 is crashing app

### ISSUE THREAD

**Issue by mnk98** [coomar2841/android-multipicker-library#181]
Getting

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kbeanie.multipicker.sample, PID: 12657
    java.lang.RuntimeException: Unable to get provider com.kbeanie.multipicker.utils.AMPFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:613)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:392)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

In Android version 8
and tried in emulator pixel 2, sdk -30, OS - 11
Same error with latest project of yours

Note- when I was trying to build the base project, got some problems with `sonatypeRepo` and `scmUrl` so I commented on these from Gradle files and it asked me to use `android.useAndroidX=true` in `gradle.properties` so I did that changes.

Build got success but app crash after run with above error

**Comment by coomar2841** [comment]
I have released a new version with the fix. `1.6.2`. Please check.

**Comment by mnk98** [comment]
Thanks, it's working now.

**Comment by mnk98** [comment]
But when i run this project in Emulator Pixel 2, OS 11, API - 30.  Selected image looks like 
![Screenshot_20210421_122819](https://user-images.githubusercontent.com/30085819/115588934-44a28980-a29d-11eb-9b19-5520aecfd323.png)

This issue happens when you select an image from gallery/downloads. But if you use via camera, it works fine

**Comment by mnk98** [comment]
Hi,
Is there anything you can fix for API 30?
