### ISSUE TITLE
Problem selecting image from Amazon, Picasa or Dropbox

### ISSUE THREAD

**Issue by erhanharm** [coomar2841/android-multipicker-library#31]
Hello,

when i try to select image from amazon. i got nullex and app crashed. 

Could you please check it 

```
`05-30 12:29:31.419 8919-8919/com.harmankaya.otokolik D/ImagePickerImpl: handleGalleryData: content://com.amazon.drive.fileprovider/original/v9c8Y9AJQqyabGWWKe5HZw/32f7eec06a5e30158153e817927f131f/IMG_9998.jpg

05-30 12:29:31.424 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: processFile: Before: Type: image, QueryUri: content://com.amazon.drive.fileprovider/original/v9c8Y9AJQqyabGWWKe5HZw/32f7eec06a5e30158153e817927f131f/IMG_9998.jpg, Original Path: null, MimeType: null, Size: 0 B Height: 0, Width: 0, Orientation: UNDEFINED

05-30 12:29:31.449 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: processFile: Path: null

05-30 12:29:31.449 8919-16067/com.harmankaya.otokolik W/System.err: java.lang.IllegalArgumentException: column 'mime_type' does not exist

05-30 12:29:31.454 8919-16067/com.harmankaya.otokolik W/System.err:     at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:303)

05-30 12:29:31.454 8919-16067/com.harmankaya.otokolik W/System.err:     at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:78)

05-30 12:29:31.454 8919-16067/com.harmankaya.otokolik W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.getAbsolutePathIfAvailable(FileProcessorThread.java:325)

05-30 12:29:31.454 8919-16067/com.harmankaya.otokolik W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:168)

05-30 12:29:31.454 8919-16067/com.harmankaya.otokolik W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:104)

05-30 12:29:31.454 8919-16067/com.harmankaya.otokolik W/System.err:     at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:78)

05-30 12:29:31.454 8919-16067/com.harmankaya.otokolik W/System.err:     at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:41)

05-30 12:29:31.504 8919-8919/com.harmankaya.otokolik I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@39102373 time:475973932

05-30 12:29:31.629 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: folder: Pictures

05-30 12:29:31.629 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: extension: null

05-30 12:29:31.629 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: mimeType: null

05-30 12:29:31.629 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: type: image

05-30 12:29:31.634 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: Out Path: /storage/emulated/0/Otodyo!/Otodyo! Pictures/IMG_9998.jpg

05-30 12:29:31.634 8919-16067/com.harmankaya.otokolik D/FileProcessorThread: processFile: Final Path: Type: image, QueryUri: content://com.amazon.drive.fileprovider/original/v9c8Y9AJQqyabGWWKe5HZw/32f7eec06a5e30158153e817927f131f/IMG_9998.jpg, Original Path: /storage/emulated/0/Otodyo!/Otodyo! Pictures/IMG_9998.jpg, MimeType: null, Size: 4.7 MB Height: 0, Width: 0, Orientation: UNDEFINED

05-30 12:29:31.634 8919-16067/com.harmankaya.otokolik D/ImageProcessorThread: postProcessImage: null

05-30 12:29:32.269 8919-16067/com.harmankaya.otokolik D/ImageProcessorThread: postProcessImage: Type: image, QueryUri: content://com.amazon.drive.fileprovider/original/v9c8Y9AJQqyabGWWKe5HZw/32f7eec06a5e30158153e817927f131f/IMG_9998.jpg, Original Path: /storage/emulated/0/Otodyo!/Otodyo! Pictures/IMG_9998.jpg, MimeType: null, Size: 4.7 MB Height: 2848, Width: 4272, Orientation: NORMAL

05-30 12:29:32.274 8919-8919/com.harmankaya.otokolik D/MainActivity: FILEPATH: null`
```

**Comment by coomar2841** [comment]
Ok. Will check this. Can you let me know which version you are using? Also, it would be helpful if you could give me the logs for Dropbox as well.

**Comment by erhanharm** [comment]
Hi ,

Here is my gradle file : 

`    compile 'com.kbeanie:multipicker:1.1.0@aar'
`

I am so sorry. Dropbox is working well.

But if i select Gallery -> an image located on Picasa - >

App is not crashed but Imagecould not get

```
05-30 12:38:19.644 20226-20226/com.harmankaya.otokolik D/ImagePickerImpl: handleGalleryData: content://com.sec.android.gallery3d.provider/picasa/item/5647371441705552482
05-30 12:38:19.689 20226-29423/com.harmankaya.otokolik D/FileProcessorThread: processFile: Before: Type: image, QueryUri: content://com.sec.android.gallery3d.provider/picasa/item/5647371441705552482, Original Path: null, MimeType: null, Size: 0 B Height: 0, Width: 0, Orientation: UNDEFINED
05-30 12:38:19.819 20226-29423/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: folder: Pictures
05-30 12:38:19.819 20226-29423/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: extension: null
05-30 12:38:19.819 20226-29423/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: mimeType: image/jpeg
05-30 12:38:19.819 20226-29423/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: type: image
05-30 12:38:19.824 20226-29423/com.harmankaya.otokolik D/FileProcessorThread: copyFileToFolder: Out Path: /storage/emulated/0/Otodyo!/Otodyo! Pictures/01 09 2011 - 1.jpg
05-30 12:38:19.824 20226-29423/com.harmankaya.otokolik D/FileProcessorThread: processFile: Final Path: Type: image, QueryUri: content://com.sec.android.gallery3d.provider/picasa/item/5647371441705552482, Original Path: /storage/emulated/0/Otodyo!/Otodyo! Pictures/01 09 2011 - 1.jpg, MimeType: image/jpeg, Size: 94.8 KB Height: 0, Width: 0, Orientation: UNDEFINED
05-30 12:38:19.824 20226-29423/com.harmankaya.otokolik D/ImageProcessorThread: postProcessImage: image/jpeg
05-30 12:38:19.894 20226-29423/com.harmankaya.otokolik D/ImageProcessorThread: postProcessImage: Type: image, QueryUri: content://com.sec.android.gallery3d.provider/picasa/item/5647371441705552482, Original Path: /storage/emulated/0/Otodyo!/Otodyo! Pictures/01 09 2011 - 1.jpg, MimeType: image/jpeg, Size: 94.8 KB Height: 640, Width: 480, Orientation: UNDEFINED
05-30 12:38:19.924 20226-20226/com.harmankaya.otokolik D/MainActivity: FILEPATH: https://lh3.googleusercontent.com/-ke-ca3WAkVk/Tl9-Z7mLimI/AAAAAAAAECo/FQwfYR17IGw/I/01%25252009%2525202011%252520-%2525201.jpg
05-30 12:38:19.924 20226-20226/com.harmankaya.otokolik E/JHEAD: can't open 'https://lh3.googleusercontent.com/-ke-ca3WAkVk/Tl9-Z7mLimI/AAAAAAAAECo/FQwfYR17IGw/I/01%25252009%2525202011%252520-%2525201.jpg'
05-30 12:38:19.924 20226-20226/com.harmankaya.otokolik E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: https:/lh3.googleusercontent.com/-ke-ca3WAkVk/Tl9-Z7mLimI/AAAAAAAAECo/FQwfYR17IGw/I/01%25252009%2525202011%252520-%2525201.jpg: open failed: ENOENT (No such file or directory)
05-30 12:38:19.959 20226-20226/com.harmankaya.otokolik I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1148cf63 time:476502385

```

**Comment by coomar2841** [comment]
Can you try the same files with the sample app and see if it is working?

**Comment by coomar2841** [comment]
Also, please let me know which device and OS version this is failing.

**Comment by erhanharm** [comment]
NO not same files different but for same choosen i always use different
files

DEVICE Samsung GalaxyNote3. N9000

OS Android 5.0 Official
30 May 2016 13:01 tarihinde "Kumar Bibek" <notifications@github.com> yazdı:

**Comment by coomar2841** [comment]
For Amazon, looks like it was able to fetch the image. 

`
05-30 12:29:32.269 8919-16067/com.harmankaya.otokolik D/ImageProcessorThread: postProcessImage: Type: image, QueryUri: content://com.amazon.drive.fileprovider/original/v9c8Y9AJQqyabGWWKe5HZw/32f7eec06a5e30158153e817927f131f/IMG_9998.jpg, Original Path: /storage/emulated/0/Otodyo!/Otodyo! Pictures/IMG_9998.jpg, MimeType: null, Size: 4.7 MB Height: 2848, Width: 4272, Orientation: NORMAL
`

Can you post the code from `onImagesChosen` method? May be some part of your code might be generating the crash.

**Comment by erhanharm** [comment]
Here is onImagesChoosen method

```
    @Override
    public void onImagesChosen(List<ChosenImage> images) {
        fileUri = Uri.parse(images.get(0).getQueryUri());
        previewMedia();

    }
```

And this is previewMedia function
```
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inSampleSize = 2;

        Cursor cursor = getActivity().getContentResolver().query(fileUri, null, null, null, null);
        if (cursor == null) { 
            finalFileURIPath = fileUri.getPath();
        } else {
            cursor.moveToFirst();
            int idx = cursor.getColumnIndex(MediaStore.Images.ImageColumns.DATA);
            finalFileURIPath = cursor.getString(idx);
            cursor.close();
        }

        Log.d(TAG, "FILEPATH: " + finalFileURIPath);

        ExifInterface exif = null;
        try {
            exif = new ExifInterface(finalFileURIPath);
        } catch (IOException e) {
            e.printStackTrace();
        }
        int orientation = 0;
        if (exif != null) {
            orientation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION,
                    ExifInterface.ORIENTATION_UNDEFINED);
        }
        final Bitmap bitmap = BitmapFactory.decodeFile(finalFileURIPath, options);
        Bitmap bmRotated = rotateBitmap(bitmap, orientation);
        imgPreview.setImageBitmap(bmRotated);
```

**Comment by coomar2841** [comment]
1. You shouldn't be using `queryUri`, since we already have a local file which you can get with `getOriginalPath`. You shouldn't be dealing with content-providers if you using this library, ideally, although you are free to do so. That might be the issue here, since the library takes care of dealing with all the different types of content providers, which are not standardized. To check that, you can check the list values by putting a breakpoint in `onImagesChosen` method, and investigate all the fields.

2. The library already generates thumbnails for you, although they are disabled by default. I guess, that's what you are trying to achieve in the `previewMedia()` function. I would suggest you to enable the flag so that you can directly get a thumbnail image to use.

`ImagePicker.shouldGenerateThumbnails(boolean generateThumbnails)`

Thumbnail path: `image.getThumbnailSmallPath()` or `image.getThumbnailPath()`

Let me know how it goes. This should solve the Amazon problem. Once you are fine with this, we can move on the Picassa problem.

**Comment by erhanharm** [comment]
Hey,

Using getOriginalPath is solved all of the problems ;)

Thanks i think we can closed this isseu. I will pusblish my app with this
library. I'll give credit to you in my credit page.

Thanks in advance.

Erhan

On Mon, May 30, 2016 at 1:56 PM, Kumar Bibek <notifications@github.com>
wrote:

>
>    1.
>
>    You shouldn't be using queryUri, since we already have a local file
>    which you can get with getOriginalPath. You shouldn't be dealing with
>    content-providers if you using this library, ideally, although you are free
>    to do so. That might be the issue here, since the library takes care of
>    dealing with all the different types of content providers, which are not
>    standardized. To check that, you can check the list values by putting a
>    breakpoint in onImagesChosen method, and investigate all the fields.
>    2.
>
>    The library already generates thumbnails for you, although they are
>    disabled by default. I guess, that's what you are trying to achieve in the
>    previewMedia() function. I would suggest you to enable the flag so
>    that you can directly get a thumbnail image to use.
>
> ImagePicker.shouldGenerateThumbnails(boolean generateThumbnails)
>
> Thumbnail path: image.getThumbnailSmallPath() or image.getThumbnailPath()
>
> Let me know how it goes. This should solve the Amazon problem. Once you
> are fine with this, we can move on the Picassa problem.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/coomar2841/android-multipicker-library/issues/31#issuecomment-222467587>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAL1JlX40x6iU5eiwNBzAhxfPD3JD50mks5qGsJrgaJpZM4Ipo1->
> .
>



-- 
*Erhan Harmankaya*

http://tr.linkedin.com/in/erhanharmankaya
