### ISSUE TITLE
Crash when selecting photo ( Android 6.0.1 Samsung Note 4)

### ISSUE THREAD

**Issue by azizimusa** [coomar2841/android-multipicker-library#36]
Here the error stacktrace.

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
       at java.io.File.fixSlashes(File.java:183)
       at java.io.File.<init>(File.java:130)
       at com.omnom.fragments.pages.PageTakeMedia.onImagesChosen(PageTakeMedia.java:422)
       at com.kbeanie.multipicker.core.threads.ImageProcessorThread$1.run(ImageProcessorThread.java:52)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7225)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

i am using plugin version
compile 'com.kbeanie:multipicker:1.1.0@aar'

**Comment by azizimusa** [comment]
Solved. It just a runtime permission issue. I've added the permission prompt and then everything working fine.
