### ISSUE TITLE
I get resource not found while it tries to fetch App Name 

### ISSUE THREAD

**Issue by amansatija** [coomar2841/android-multipicker-library#44]
I get Resource not found after picking the pic from gallery!!!
on further debugging i found the library was crashing on a very simple thing , which was when it was trying to fetch app name from ApplicationInfo ,
funny part was ur sample app works seamlessly on my phone and blue stacks 
but ur library integrated crashes...!!
wat is the best solution u propose ..!!

**Comment by coomar2841** [comment]
Can you send me complete logs? Are you running on 6.0? Might be a permissions issue. Device and OS versions information also might help.

**Comment by mohn93** [comment]
same bug 
this is the logs 

` FATAL EXCEPTION: Thread-230
                                                                Process: ly.neon.daleel, PID: 23898
                                                                android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                                    at android.content.res.Resources.getText(Resources.java:299)
                                                                    at android.content.res.Resources.getString(Resources.java:385)
                                                                    at android.content.Context.getString(Context.java:377)
                                                                    at com.kbeanie.multipicker.utils.FileUtils.getAppName(FileUtils.java:56)
                                                                    at com.kbeanie.multipicker.utils.FileUtils.getExternalFilesDirectory(FileUtils.java:37)
                                                                    at com.kbeanie.multipicker.core.threads.FileProcessorThread.getTargetDirectory(FileProcessorThread.java:490)
                                                                    at com.kbeanie.multipicker.core.threads.FileProcessorThread.generateFileName(FileProcessorThread.java:577)
                                                                    at com.kbeanie.multipicker.core.threads.FileProcessorThread.getFromContentProvider(FileProcessorThread.java:246)
                                                                    at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:174)
                                                                    at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
                                                                    at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)
                                                                    at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:41)`

**Comment by coomar2841** [comment]
OS Version?

**Comment by mohn93** [comment]
API 22, and 24

**Comment by coomar2841** [comment]
can you confirm if your application tag in manifest file has a label specified?

**Comment by coomar2841** [comment]
That seems to be the issue. I will fix this in the next release. Till then, if it is possible, can you specify the label in the application tag for your application? That should take care of this issue.

**Comment by mohn93** [comment]
Yes i set the label and it works ,but it wont work if i set the label to be just in arabic languege, thank you

**Comment by coomar2841** [comment]
You can try the beta build for now.

```
compile 'com.kbeanie:multipicker:1.1.21-beta@aar'
```
