### ISSUE TITLE
Bug: resource leak found in strict mode

### ISSUE THREAD

**Issue by umesh0492** [coomar2841/android-multipicker-library#60]
**Strict mode configuration** 
```
StrictMode.setThreadPolicy (new StrictMode.ThreadPolicy.Builder ()
.detectDiskReads ()
.detectDiskWrites ()
.detectNetwork ()
.detectAll ()// or .detectAll() for all detectable problems
.penaltyLog ()
.build ());
StrictMode.setVmPolicy (new StrictMode.VmPolicy.Builder ()
.detectLeakedSqlLiteObjects ()
.detectLeakedClosableObjects ()
.penaltyLog ()
.penaltyDeath ()
.build ());
```

**Logcat**
 
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'close' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:180)
at java.io.FileInputStream.(FileInputStream.java:78)
at java.io.FileInputStream.(FileInputStream.java:103)
at android.media.ExifInterface.loadAttributes(ExifInterface.java:1342)
at android.media.ExifInterface.(ExifInterface.java:1061)
at com.kbeanie.multipicker.core.threads.FileProcessorThread.getHeightOfImage(FileProcessorThread.java:779)
at com.kbeanie.multipicker.core.threads.ImageProcessorThread.generateMetadata(ImageProcessorThread.java:96)
at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImage(ImageProcessorThread.java:81)
at com.kbeanie.multipicker.core.threads.ImageProcessorThread.postProcessImages(ImageProcessorThread.java:65)
at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:42)

**Comment by coomar2841** [comment]
Does it happen while selecting a picture from Gallery which has a content uri or from another application having a file uri? I wasn't able to reproduce this problem. Also, please let me know the OS version.
