### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by tree1891** [coomar2841/android-multipicker-library#79]
I use v1.1.13 and sometimes see below.
`Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 clip={text/uri-list U:file:///storage/emulated/0/%D8%B4%D8%BA%D9%91%D9%84%D9%86%D9%8A/%D8%B4%D8%BA%D9%91%D9%84%D9%86%D9%8A%20Pictures/b698b59d-79b4-4cf9-9189-baac83b21099.jpeg} (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1534)
       at android.app.Activity.startActivityForResult(Activity.java:3968)
       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
       at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:31)
       at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:169)
       at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:934)
       at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1043)
       at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:951)
       at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:940)
       at com.kbeanie.multipicker.core.PickerManager.pickInternal(PickerManager.java:174)
       at com.kbeanie.multipicker.core.ImagePickerImpl.takePictureWithCamera(ImagePickerImpl.java:157)
       at com.kbeanie.multipicker.core.ImagePickerImpl.pick(ImagePickerImpl.java:121)
       at com.kbeanie.multipicker.api.CameraImagePicker.pickImage(CameraImagePicker.java:81)
       at com.shaghalni.shaghalni.Post3Fragment.onClickCapture(Post3Fragment.java:223)
       at com.shaghalni.shaghalni.Post3Fragment$2$1.onMenuItemClick(Post3Fragment.java:151)
...`

**Comment by coomar2841** [comment]
Do you know which device and os this is on?

**Comment by tree1891** [comment]
Device: LAVA iris 870s
OS: 6.0

**Comment by deepbhavsar** [comment]
I am facing issue into the below device @coomar2841

**Device**
Brand: TrendMicro
Model: GI-I9500_TMMARS
Orientation: Portrait
RAM free: 20.64 GB
Disk free: 40.09 GB
**Operating System**
Version: 5.1
Orientation: Portrait
Rooted: Yes
