### ISSUE TITLE
crash when choosing media from SkyDrive/OneDrive

### ISSUE THREAD

**Issue by virengujariya** [coomar2841/android-multipicker-library#81]
```at android.os.Parcel.readException(Parcel.java:1636)
	at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerProxy.java:4263)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:5475)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2267)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1515)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1129)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:982)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:835)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:789)
	at com.kbeanie.multipicker.core.threads.FileProcessorThread.getFromContentProvider(FileProcessorThread.java:249)
	at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:174)
	at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
	at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)```

**Comment by coomar2841** [comment]
Can you post the OS version and device? This is from MediaPicker?

**Comment by virengujariya** [comment]
Yes it is from MediaPicker. Device is Moto G(4) Plus and Android OS 7.0

**Comment by coomar2841** [comment]
Ok. Will check this.

**Comment by coomar2841** [comment]
Does picking only images work?

**Comment by virengujariya** [comment]
@coomar2841 Sorry missed your message. No images don't work either.

**Comment by virengujariya** [comment]
@coomar2841 Correction. photos from OneDrive works!

**Comment by justincpollard** [comment]
I'm seeing a few crashes in my production app as well. Just like @virengujariya, this crash comes from a Moto G (4), but my user is running Android 6.0.1. Here's the stacktrace:

```
Fatal Exception: java.lang.SecurityException: Permission Denial: opening provider com.microsoft.skydrive.content.MetadataContentProvider from ProcessRecord{4846fb7 13572:com.padmapper.search/u0a116} (pid=13572, uid=10116) that is not exported from uid 10180
       at android.os.Parcel.readException(Parcel.java:1620)
       at android.os.Parcel.readException(Parcel.java:1573)
       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3605)
       at android.app.ActivityThread.acquireProvider(ActivityThread.java:4799)
       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1466)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1087)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:942)
       at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:795)
       at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:749)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.getFromContentProvider(FileProcessorThread.java:249)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFile(FileProcessorThread.java:174)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.processFiles(FileProcessorThread.java:105)
       at com.kbeanie.multipicker.core.threads.FileProcessorThread.run(FileProcessorThread.java:79)
       at com.kbeanie.multipicker.core.threads.ImageProcessorThread.run(ImageProcessorThread.java:41)
```

**Comment by virengujariya** [comment]
@justincpollard thanks for pointing out device info. Actually I am having trouble on the same device. 

@coomar2841 ^ FYI

**Comment by coomar2841** [comment]
Still trying to figure this out. Seems they have disabled file picking from sky drive directly. They probably want to force to use their SDK.

**Comment by virengujariya** [comment]
@coomar2841 at-least for now it should return error instead of crash.
