### ISSUE TITLE
ActivityNotFoundException 

### ISSUE THREAD

**Issue by ldemay** [coomar2841/android-multipicker-library#89]
```
x D/dalvikvm: DexOpt: couldn't find static field Landroid/os/Environment;.DIRECTORY_DOCUMENTS
x W/dalvikvm: VFY: unable to resolve static field 170 (DIRECTORY_DOCUMENTS) in Landroid/os/Environment;
x D/dalvikvm: VFY: replacing opcode 0x62 at 0x0023
x D/AndroidRuntime: Shutting down VM
x W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa669e228)
system_process I/ActivityManager: START {act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=application/pdf flg=0x1 u=0} from pid 5246

x E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.GET_CONTENT cat=[android.intent.category.OPENABLE] typ=application/pdf flg=0x1 }
                                                                            at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1545)
                                                                            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1416)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:3351)
                                                                            at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                            at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                            at android.app.Activity.startActivityForResult(Activity.java:3312)
                                                                            at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                            at com.kbeanie.multipicker.core.PickerManager.pickInternal(PickerManager.java:172)
                                                                            at com.kbeanie.multipicker.api.FilePicker.pick(FilePicker.java:106)
                                                                            at com.kbeanie.multipicker.api.FilePicker.pickFile(FilePicker.java:84)
```

Running 'com.kbeanie:multipicker:1.1.31@aar'
on Android Simulator running API 16, works well otherwise.

**Comment by coomar2841** [comment]
On simulator, may be there's no application that can handle pdf files.
