### ISSUE TITLE
In Tablets its is crashing

### ISSUE THREAD

**Issue by abakashaGit** [coomar2841/android-multipicker-library#92]
java.lang.NoClassDefFoundError: storage.StoragePreferences
                                                                               at com.kbeanie.multipicker.core.PickerManager.initProperties(PickerManager.java:67)
                                                                                at com.kbeanie.multipicker.core.PickerManager.<init>(PickerManager.java:51)
                                                                                at com.kbeanie.multipicker.core.VideoPickerImpl.<init>(VideoPickerImpl.java:39)
                                                                                at com.kbeanie.multipicker.api.VideoPicker.<init>(VideoPicker.java:19)

**Comment by coomar2841** [comment]
Can you try this? ```compile 'com.kbeanie:multipicker:1.1.4-beta@aar```

**Comment by coomar2841** [comment]
Did this fix the issue?

**Comment by vigneshwaran-ms** [comment]
I faced the same issue and the problem was I have not enabled multidex enabled and my app had more than 65k methods (Too much of libraries). Try to enable multidex in your app and extend MultidexApplication if you have custom Application class implementation.
