### ISSUE TITLE
library conflict issue

### ISSUE THREAD

**Issue by rahulpawar1989** [coomar2841/android-multipicker-library#93]
Hi 
I am using below libraries

compile 'com.android.support:design:24.1.1'
compile 'com.kbeanie:multipicker:1.1.31@aar'

in my project. Its compiling and when i run it on my android device, image picker is not initializing properly and giving below error

 java.lang.NoClassDefFoundError: storage.StoragePreferences
at com.kbeanie.multipicker.core.PickerManager.initProperties(PickerManager.java:67)
at com.kbeanie.multipicker.core.PickerManager.<init>(PickerManager.java:51)
at com.kbeanie.multipicker.core.ImagePickerImpl.<init>(ImagePickerImpl.java:47)
 at com.kbeanie.multipicker.api.ImagePicker.<init>(ImagePicker.java:18)

But if i remove below library
compile 'com.android.support:design:24.1.1'
then multipicker library is working fine. 

But i need both to be in my project. So Please give me solution for solving this.

Thanks in advance..

**Comment by coomar2841** [comment]
Can you try this? ```compile 'com.kbeanie:multipicker:1.1.4-beta@aar```

**Comment by rahulpawar1989** [comment]
Thanks for d reply.
Ok I will try now..

**Comment by rahulpawar1989** [comment]
I tried but its not building and its giving error as
Failed to resolve:com.kbeanie:multipicker:1.1.4-beta

**Comment by coomar2841** [comment]
Can you try after sometime? May be it's not available yet on the repos.


*Thanks and Regards,Kumar Bibek*


*http://techdroid.kbeanie.com
<http://techdroid.kbeanie.com>http://www.kbeanie.com
<http://www.kbeanie.com>*

**Comment by rahulpawar1989** [comment]
Ok ..I will try after sometime..

Tq

**Comment by rahulpawar1989** [comment]
Sir,

I am still getting same error as

Failed to resolve:com.kbeanie:multipicker:1.1.4-beta

Please guide me.

Thanks
Rahul

On 22-Mar-2017 1:49 PM, "Rahul Pawar" <rahulp9538@gmail.com> wrote:

Ok ..I will try after sometime..

Tq

**Comment by rahulpawar1989** [comment]
Sir repo is up now. my projects compiles properly. But still same problem exists i.e.
 java.lang.NoClassDefFoundError: storage.StoragePreferences
  at com.kbeanie.multipicker.core.PickerManager.initProperties(PickerManager.java:67)
at com.kbeanie.multipicker.core.PickerManager.<init>(PickerManager.java:51)
  at com.kbeanie.multipicker.core.ImagePickerImpl.<init>(ImagePickerImpl.java:47)
  at com.kbeanie.multipicker.api.ImagePicker.<init>(ImagePicker.java:18)

for your help here by i am attaching my gradle file

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "gradl1.com.myapplication"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        renderscriptTargetApi 19
        renderscriptSupportModeEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    lintOptions {
        disable "ResourceType"
        disable 'InvalidPackage'
        abortOnError false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.0'
    testCompile 'junit:junit:4.12'
    compile 'com.google.android.gms:play-services-ads:9.6.1'
    compile 'com.android.support:appcompat-v7:25.2.1'
    compile 'com.romainpiel.shimmer:library:1.4.0@aar'
    compile 'com.android.support:support-v4:25.2.1'
    compile 'io.reactivex:rxjava:1.0.+'
    compile 'io.reactivex:rxandroid:0.23.+'
    compile 'com.squareup.retrofit:retrofit:1.8.+'
    compile 'com.squareup.okio:okio:1.1.+'
    compile 'com.squareup.okhttp:okhttp:2.1.+'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.1.+'
    compile 'de.keyboardsurfer.android.widget:crouton:1.8.5@jar'
    compile files('libs/FacebookAdapter.jar')
    compile 'com.google.code.gson:gson:2.8.0'
    compile 'com.etsy.android.grid:library:1.0.5'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.github.clans:fab:1.6.4'
    compile 'com.afollestad.material-dialogs:core:0.9.2.3'
    compile 'com.facebook.android:facebook-android-sdk:4.18.0'
    compile 'com.facebook.android:audience-network-sdk:4.18.0'
    compile 'com.android.support:support-v4:24.2.1'
    compile 'com.github.yesidlazaro:GmailBackground:1.1'
    compile 'com.google.android.gms:play-services-ads:9.4.0'
     compile 'com.google.android.gms:play-services-ads:9.4.0'
    compile 'com.android.support:cardview-v7:24.1.1'
    compile 'com.android.support:recyclerview-v7:24.1.1'
    compile 'com.android.support:appcompat-v7:24.1.1'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.android.support:design:25.3.0'
    compile('com.mopub:mopub-sdk-native-static:4.11.0@aar') {
        exclude group:'com.android.support', module:'appcompat-v7'
        exclude group:'com.android.support', module:'recyclerview-v7'
        transitive = true
    }
//File picker
    compile 'com.kbeanie:multipicker:1.1.4-beta@aar'
}

**Comment by coomar2841** [comment]
Can you do a clean build and try? I am suspecting this is probably because of multidex application. Can you see if by removing any other library, if it fixes the issue?

**Comment by rahulpawar1989** [comment]
Hi sir

Yes .I made a clean build and re build.but it's still giving same problem.
One thing I saw that when I remove

compile 'com.android.support:design:24.1.1'

From my project's gradle your multiple picker works successfully . But
according to my project requirements I need above library.

So please help me out sir..

Thanks



On 22-Mar-2017 8:49 PM, "Kumar Bibek" <notifications@github.com> wrote:

Can you do a clean build and try? I am suspecting this is probably because
of multidex application. Can you see if by removing any other library, if
it fixes the issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/coomar2841/android-multipicker-library/issues/93#issuecomment-288432382>,
or mute the thread
